### PR TITLE
Place CDATA tags between comments to avoid confusing older browsers.

### PR DESCRIPTION
**Pull request by gustavolobo**

### CODE REVIEW

**Comment by hlascelles** [comment]
:+1: Definitely like to get this in - chrome reports it as an error.

**Comment by hlascelles** [comment]
Can this make it in please? We're still running off the git branch, and would like to move back to the official gem.

**Comment by paolochiodi** [comment]
Thank you very much for the PR and sorry for taking so long to act.

**Comment by paolochiodi** [comment]
New version (0.3.0) published

**Pull request merged**
